# Generated by Django 5.1 on 2024-09-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACADEMIC_YEAR', models.IntegerField(max_length=4)),
                ('SEMESTER', models.IntegerField(max_length=1)),
            ],
        ),
    ]
