# Generated by Django 5.1 on 2024-09-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgsi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentInfo',
        ),
    ]
